<?xml version="1.0"?>
<robot name="omni_1" xmlns:xacro="http://wiki.ros.org/xacro">

  <!-- MATERIAL DEFINITIONS -->
  <material name="white">
    <color rgba="1 1 1 1"/>  <!-- White -->
  </material>
  <material name="copper">
    <color rgba="0.72 0.45 0.20 1"/>  <!-- Copper -->
  </material>

  <!-- BASE LINK (CYLINDER) -->
  <link name="base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.11" length="0.064"/>  <!-- 220mm dia, 64mm height -->
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.11" length="0.064"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <!-- OMNI WHEEL MACRO -->
  <xacro:macro name="omni_wheel" params="name x y angle">
    <link name="${name}">
      <visual>
        <origin rpy="0 1.5708 0" xyz="0 0 0"/>  <!-- Wheel rotation -->
        <geometry>
          <cylinder radius="0.04" length="0.02"/>  <!-- 80mm dia, 20mm thick -->
        </geometry>
        <material name="copper"/>
      </visual>

      <!-- 8 ROLLERS, TANGENTIAL TO WHEEL -->
      <xacro:property name="roller_radius" value="0.005"/>
      <xacro:property name="roller_length" value="0.02"/>
      <xacro:property name="wheel_radius" value="0.04"/>
      
      <!-- Roller 1: 0° -->
      <visual>
        <origin xyz="0 ${wheel_radius} 0" rpy="0 0 0"/>
        <geometry><cylinder radius="${roller_radius}" length="${roller_length}"/></geometry>
        <material name="white"/>  <!-- Explicitly set to white -->
      </visual>
      
      <!-- Roller 2: 45° -->
      <visual>
        <origin xyz="0 ${wheel_radius*cos(0.7854)} ${wheel_radius*sin(0.7854)}" rpy="0.7854 0 0"/>
        <geometry><cylinder radius="${roller_radius}" length="${roller_length}"/></geometry>
        <material name="white"/>  <!-- Explicitly set to white -->
      </visual>
      
      <!-- Roller 3: 90° -->
      <visual>
        <origin xyz="0 0 ${wheel_radius}" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${roller_radius}" length="${roller_length}"/></geometry>
        <material name="white"/>  <!-- Explicitly set to white -->
      </visual>
      
      <!-- Roller 4: 135° -->
      <visual>
        <origin xyz="0 ${-wheel_radius*cos(0.7854)} ${wheel_radius*sin(0.7854)}" rpy="2.3562 0 0"/>
        <geometry><cylinder radius="${roller_radius}" length="${roller_length}"/></geometry>
        <material name="white"/>  <!-- Explicitly set to white -->
      </visual>
      
      <!-- Roller 5: 180° -->
      <visual>
        <origin xyz="0 ${-wheel_radius} 0" rpy="3.1416 0 0"/>
        <geometry><cylinder radius="${roller_radius}" length="${roller_length}"/></geometry>
        <material name="white"/>  <!-- Explicitly set to white -->
      </visual>
      
      <!-- Roller 6: 225° -->
      <visual>
        <origin xyz="0 ${-wheel_radius*cos(0.7854)} ${-wheel_radius*sin(0.7854)}" rpy="3.927 0 0"/>
        <geometry><cylinder radius="${roller_radius}" length="${roller_length}"/></geometry>
        <material name="white"/>  <!-- Explicitly set to white -->
      </visual>
      
      <!-- Roller 7: 270° -->
      <visual>
        <origin xyz="0 0 ${-wheel_radius}" rpy="4.7124 0 0"/>
        <geometry><cylinder radius="${roller_radius}" length="${roller_length}"/></geometry>
        <material name="white"/>  <!-- Explicitly set to white -->
      </visual>
      
      <!-- Roller 8: 315° -->
      <visual>
        <origin xyz="0 ${wheel_radius*cos(0.7854)} ${-wheel_radius*sin(0.7854)}" rpy="5.4978 0 0"/>
        <geometry><cylinder radius="${roller_radius}" length="${roller_length}"/></geometry>
        <material name="white"/>  <!-- Explicitly set to white -->
      </visual>

      <collision>
        <geometry>
          <cylinder radius="0.04" length="0.02"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.15"/>
        <inertia ixx="0.0002" ixy="0" ixz="0" iyy="0.0002" iyz="0" izz="0.0002"/>
      </inertial>
    </link>

    <!-- WHEEL ORIENTATION -->
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} -0.02" rpy="0 0 ${angle}"/>
      <axis xyz="1 0 0"/>
    </joint>
  </xacro:macro>

  <!-- THREE WHEELS AT 120° INTERVALS -->
  <xacro:omni_wheel name="wheel_0" x="0.13" y="0" angle="0"/>         <!-- 0° -->
  <xacro:omni_wheel name="wheel_120" x="-0.065" y="0.11258" angle="2.0944"/>  <!-- 120° -->
  <xacro:omni_wheel name="wheel_240" x="-0.065" y="-0.11258" angle="-2.0944"/> <!-- 240° -->

</robot>