#!/bin/bash

# Prepare device arguments (e.g. USB serial devices)
device_args=()
if compgen -G "/dev/ttyUSB*" > /dev/null; then
    for device in /dev/ttyUSB*; do
        device_args+=("--device=$device:$device")
    done
fi

podman run -it --rm \
    -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
    -v ros2-volume:/home/hostuser \
    -e DISPLAY=$DISPLAY \
    -e WAYLAND_DISPLAY=$WAYLAND_DISPLAY \
    -e XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
    -e PULSE_SERVER=$PULSE_SERVER \
    -v /mnt/wslg:/mnt/wslg \
    --security-opt label=disable \
    --group-add=video \
    --network=host \
    "${device_args[@]}" \
    ros2-humble-container
